In [1]:
import yfinance as yf
import pandas as pd 
import datetime as dt

In [42]:
stock = 'AAPL'

In [27]:
intraday = yf.download(stock, start = '2021-03-25', end= '2021-03-26', interval = '1m')

[*********************100%***********************]  1 of 1 completed

In [28]:
intraday

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-03-25 09:00:00+01:00,62.750000,62.750000,61.650002,62.200001,62.200001,0
2021-03-25 09:01:00+01:00,62.400002,63.049999,62.349998,62.750000,62.750000,8426
2021-03-25 09:02:00+01:00,62.750000,62.750000,62.750000,62.750000,62.750000,143
2021-03-25 09:03:00+01:00,62.599998,62.599998,62.299999,62.400002,62.400002,1938
2021-03-25 09:04:00+01:00,62.400002,62.700001,62.349998,62.500000,62.500000,2369
...,...,...,...,...,...,...
2021-03-25 17:25:00+01:00,61.900002,61.950001,61.900002,61.950001,61.950001,3651
2021-03-25 17:26:00+01:00,61.950001,62.049999,61.950001,62.000000,62.000000,1622
2021-03-25 17:27:00+01:00,62.000000,62.000000,61.900002,62.000000,62.000000,3229
2021-03-25 17:28:00+01:00,62.000000,62.049999,62.000000,62.049999,62.049999,1305
2021-03-25 17:29:00+01:00,62.049999,62.299999,62.000000,62.299999,62.299999,1786

In [5]:
intraday.iloc[120].Open/intraday.iloc[0].Open -1

-0.018023160300515095

In [29]:
def Intradaytrend(df, entry, exit):
    ret_120min = df.iloc[120].Open/df.iloc[0].Open -1
    tickret = df.Open.pct_change()
    if ret_120min > entry:
        buyprice = df.iloc[121].Open
        buytime = df.iloc[121].name
        cumulated = (tickret.loc[buytime:] + 1).cumprod()-1
        exittime = cumulated[(cumulated < -exit) | (cumulated > exit)].first_valid_index()
        if exittime == None:
            exitprice = df.iloc[-1].Open
        else:
            exitprice = df.loc[exittime + dt.timedelta(minutes = 1)].Open
        profit = exitprice - buyprice
        profitrel = profit/buyprice
        return profitrel
    else:
        return None

In [30]:
Intradaytrend(intraday, 0.01, 0.01)

In [104]:
stock = 'AMD'
dates = yf.download(stock, start= '2021-03-07', end='2021-04-07')
frame = []
for i in dates.index:
    frame.append(yf.download(stock, start= i, end=i + dt.timedelta(days =1), interval = '1m'))

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- AMD: 1m data not available for startTime=1615161600 and endTime=1615248000. The requested range must be within the last 30 days.
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- AMD: 1m data not available for startTime=1615248000 and endTime=1615334400. The requested range must be within the last 30 days.
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [107]:
del frame[0:1]

In [108]:
returns = []
for i in frame:
    returns.append(Intradaytrend(i, 0.01, 0.02))

In [109]:
returns

[None,
 0.00373716778084689,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 -0.02053267928083195,
 None,
 None,
 None,
 None,
 0.0037089257765999385,
 None,
 None,
 -0.012629033816608622]

In [101]:
frame

[Empty DataFrame
 Columns: [Open, High, Low, Close, Adj Close, Volume]
 Index: [],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-11 09:30:00-05:00  79.894997  79.902000  79.553001  79.555000
 2021-03-11 09:31:00-05:00  79.559998  80.190002  79.559998  79.800003
 2021-03-11 09:32:00-05:00  79.800003  79.959999  79.550003  79.754997
 2021-03-11 09:33:00-05:00  80.000000  80.080002  79.995003  80.008301
 2021-03-11 09:34:00-05:00  80.000000  80.199997  79.989998  80.165001
 ...                              ...        ...        ...        ...
 2021-03-11 15:55:00-05:00  81.245003  81.300003  81.160004  81.160004
 2021-03-11 15:56:00-05:00  81.150002  81.169998  81.120003  81.149902
 2021-03-11 15:57:00-05:00  81.139999  81.199997  81.099998  81.172302
 2021-03-11 15:58:00-05:00  81.180000  81.199997  81.144997  81.199997
 2021-03-11 15:59:00-05:00  81.192299  81.279999  81.169998  81.230003

                            Adj Close   Volume
 Datetime
 2021-03-11 09:30:00-05:00  79.555000  1452189
 2021-03-11 09:31:00-05:00  79.800003   457421
 2021-03-11 09:32:00-05:00  79.754997   266560
 2021-03-11 09:33:00-05:00  80.008301   319058
 2021-03-11 09:34:00-05:00  80.165001   286549
 ...                              ...      ...
 2021-03-11 15:55:00-05:00  81.160004   105098
 2021-03-11 15:56:00-05:00  81.149902   130000
 2021-03-11 15:57:00-05:00  81.172302   177417
 2021-03-11 15:58:00-05:00  81.199997   161299
 2021-03-11 15:59:00-05:00  81.230003   375938

 [389 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-12 09:30:00-05:00  79.849998  79.849998  79.709999  79.720001
 2021-03-12 09:31:00-05:00  79.459999  80.010002  79.320000  79.930000
 2021-03-12 09:32:00-05:00  79.894997  80.000000  79.690002  79.790001
 2021-03-12 09:33:00-05:00  79.779999  79.780098  79.750000  79.780098
 2021-03-12 09:34:00-05:00  79.669998  79.849998  79.660004  79.690002
 ...                              ...        ...        ...        ...
 2021-03-12 15:55:00-05:00  80.860001  80.949997  80.860001  80.910004
 2021-03-12 15:56:00-05:00  80.919998  81.089996  80.919998  81.089996
 2021-03-12 15:57:00-05:00  81.089996  81.095001  80.940002  80.985001
 2021-03-12 15:58:00-05:00  80.980003  81.080002  80.974998  81.080002
 2021-03-12 15:59:00-05:00  81.080002  81.089996  80.989998  81.050003

                            Adj Close   Volume
 Datetime
 2021-03-12 09:30:00-05:00  79.720001  1254967
 2021-03-12 09:31:00-05:00  79.930000   452677
 2021-03-12 09:32:00-05:00  79.790001   217953
 2021-03-12 09:33:00-05:00  79.780098   192481
 2021-03-12 09:34:00-05:00  79.690002   266406
 ...                              ...      ...
 2021-03-12 15:55:00-05:00  80.910004   140454
 2021-03-12 15:56:00-05:00  81.089996   137327
 2021-03-12 15:57:00-05:00  80.985001   230803
 2021-03-12 15:58:00-05:00  81.080002   172310
 2021-03-12 15:59:00-05:00  81.050003   351526

 [390 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-15 09:30:00-04:00  81.930000  81.930000  81.930000  81.930000
 2021-03-15 09:31:00-04:00  81.940002  81.940002  81.519997  81.790001
 2021-03-15 09:32:00-04:00  81.790001  81.849998  81.489998  81.639900
 2021-03-15 09:33:00-04:00  81.800003  81.879997  81.800003  81.849998
 2021-03-15 09:34:00-04:00  82.000000  82.010002  81.919998  81.919998
 ...                              ...        ...        ...        ...
 2021-03-15 15:55:00-04:00  82.369904  82.440002  82.360001  82.379997
 2021-03-15 15:56:00-04:00  82.379997  82.410004  82.349998  82.370003
 2021-03-15 15:57:00-04:00  82.379997  82.440002  82.370003  82.400002
 2021-03-15 15:58:00-04:00  82.410004  82.410004  82.360001  82.380096
 2021-03-15 15:59:00-04:00  82.385002  82.570000  82.349998  82.510002

                            Adj Close  Volume
 Datetime
 2021-03-15 09:30:00-04:00  81.930000  876654
 2021-03-15 09:31:00-04:00  81.790001  215090
 2021-03-15 09:32:00-04:00  81.639900  272688
 2021-03-15 09:33:00-04:00  81.849998  278470
 2021-03-15 09:34:00-04:00  81.919998  220547
 ...                              ...     ...
 2021-03-15 15:55:00-04:00  82.379997  172278
 2021-03-15 15:56:00-04:00  82.370003  160136
 2021-03-15 15:57:00-04:00  82.400002  248860
 2021-03-15 15:58:00-04:00  82.380096  225761
 2021-03-15 15:59:00-04:00  82.510002  547920

 [389 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-16 09:30:00-04:00  83.660004  83.660004  83.136703  83.379997
 2021-03-16 09:31:00-04:00  83.361000  83.361000  83.099998  83.285004
 2021-03-16 09:32:00-04:00  83.285004  83.769997  83.285004  83.420700
 2021-03-16 09:33:00-04:00  84.019997  84.114998  84.019997  84.114998
 2021-03-16 09:34:00-04:00  84.000000  84.210098  84.000000  84.199997
 ...                              ...        ...        ...        ...
 2021-03-16 15:55:00-04:00  82.800003  82.809998  82.639999  82.699997
 2021-03-16 15:56:00-04:00  82.699997  82.739998  82.584999  82.584999
 2021-03-16 15:57:00-04:00  82.589996  82.709999  82.550003  82.595001
 2021-03-16 15:58:00-04:00  82.589996  82.660004  82.589996  82.654999
 2021-03-16 15:59:00-04:00  82.650002  82.779999  82.639999  82.769997

                            Adj Close   Volume
 Datetime
 2021-03-16 09:30:00-04:00  83.379997  1099009
 2021-03-16 09:31:00-04:00  83.285004   281595
 2021-03-16 09:32:00-04:00  83.420700   602807
 2021-03-16 09:33:00-04:00  84.114998   652684
 2021-03-16 09:34:00-04:00  84.199997   412134
 ...                              ...      ...
 2021-03-16 15:55:00-04:00  82.699997   280402
 2021-03-16 15:56:00-04:00  82.584999   194694
 2021-03-16 15:57:00-04:00  82.595001   183702
 2021-03-16 15:58:00-04:00  82.654999   143796
 2021-03-16 15:59:00-04:00  82.769997   336857

 [390 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-17 09:30:00-04:00  81.750000  81.750000  81.269997  81.440002
 2021-03-17 09:31:00-04:00  81.419998  81.889999  81.410004  81.839996
 2021-03-17 09:32:00-04:00  81.839699  81.989998  81.680000  81.809998
 2021-03-17 09:33:00-04:00  81.750000  81.806000  81.730003  81.740097
 2021-03-17 09:34:00-04:00  81.919998  81.919998  81.690102  81.690102
 ...                              ...        ...        ...        ...
 2021-03-17 15:55:00-04:00  82.500000  82.510002  82.370003  82.409897
 2021-03-17 15:56:00-04:00  82.419998  82.535004  82.419998  82.489998
 2021-03-17 15:57:00-04:00  82.500000  82.559998  82.430000  82.540100
 2021-03-17 15:58:00-04:00  82.550003  82.620003  82.519997  82.589996
 2021-03-17 15:59:00-04:00  82.599998  82.668404  82.599998  82.639999

                            Adj Close  Volume
 Datetime
 2021-03-17 09:30:00-04:00  81.440002  942829
 2021-03-17 09:31:00-04:00  81.839996  169487
 2021-03-17 09:32:00-04:00  81.809998  190307
 2021-03-17 09:33:00-04:00  81.740097  192611
 2021-03-17 09:34:00-04:00  81.690102  174670
 ...                              ...     ...
 2021-03-17 15:55:00-04:00  82.409897  115347
 2021-03-17 15:56:00-04:00  82.489998  153746
 2021-03-17 15:57:00-04:00  82.540100  163995
 2021-03-17 15:58:00-04:00  82.589996  158489
 2021-03-17 15:59:00-04:00  82.639999  274670

 [389 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-18 09:30:00-04:00  81.055000  81.620003  80.980003  81.199997
 2021-03-18 09:31:00-04:00  81.199997  81.449898  80.879997  80.889999
 2021-03-18 09:32:00-04:00  80.900002  81.129997  80.769997  81.110100
 2021-03-18 09:33:00-04:00  81.129997  81.180000  80.919998  81.014999
 2021-03-18 09:34:00-04:00  81.022400  81.150002  80.919998  81.080002
 ...                              ...        ...        ...        ...
 2021-03-18 15:55:00-04:00  78.089996  78.138397  78.019997  78.070000
 2021-03-18 15:56:00-04:00  78.070000  78.129997  78.010002  78.084999
 2021-03-18 15:57:00-04:00  78.089996  78.180000  78.080002  78.095001
 2021-03-18 15:58:00-04:00  78.099998  78.169998  78.072998  78.160004
 2021-03-18 15:59:00-04:00  78.169998  78.180000  78.099998  78.129997

                            Adj Close   Volume
 Datetime
 2021-03-18 09:30:00-04:00  81.199997  1061537
 2021-03-18 09:31:00-04:00  80.889999   298937
 2021-03-18 09:32:00-04:00  81.110100   206906
 2021-03-18 09:33:00-04:00  81.014999   160197
 2021-03-18 09:34:00-04:00  81.080002   125559
 ...                              ...      ...
 2021-03-18 15:55:00-04:00  78.070000   423013
 2021-03-18 15:56:00-04:00  78.084999   343583
 2021-03-18 15:57:00-04:00  78.095001   519345
 2021-03-18 15:58:00-04:00  78.160004   286491
 2021-03-18 15:59:00-04:00  78.129997   438119

 [388 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-19 09:30:00-04:00  78.419998  78.419998  78.410004  78.410004
 2021-03-19 09:31:00-04:00  78.459999  79.019699  78.430000  78.930000
 2021-03-19 09:32:00-04:00  78.930000  79.070000  78.750000  78.910004
 2021-03-19 09:33:00-04:00  78.919998  79.089996  78.849998  79.000999
 2021-03-19 09:34:00-04:00  79.169998  79.209999  78.910103  78.940002
 ...                              ...        ...        ...        ...
 2021-03-19 15:55:00-04:00  79.040001  79.099998  78.949997  79.014999
 2021-03-19 15:56:00-04:00  79.010002  79.040001  78.910004  79.035004
 2021-03-19 15:57:00-04:00  79.040001  79.110001  79.029999  79.050003
 2021-03-19 15:58:00-04:00  79.059998  79.059998  78.940002  78.980003
 2021-03-19 15:59:00-04:00  78.970001  79.110001  78.930000  79.059998

                            Adj Close   Volume
 Datetime
 2021-03-19 09:30:00-04:00  78.410004  1889947
 2021-03-19 09:31:00-04:00  78.930000   272464
 2021-03-19 09:32:00-04:00  78.910004   189397
 2021-03-19 09:33:00-04:00  79.000999   200155
 2021-03-19 09:34:00-04:00  78.940002   221674
 ...                              ...      ...
 2021-03-19 15:55:00-04:00  79.014999   290913
 2021-03-19 15:56:00-04:00  79.035004   342598
 2021-03-19 15:57:00-04:00  79.050003   402919
 2021-03-19 15:58:00-04:00  78.980003   419023
 2021-03-19 15:59:00-04:00  79.059998   932153

 [389 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-22 09:30:00-04:00  79.989998  80.430000  79.989998  80.339996
 2021-03-22 09:31:00-04:00  80.349899  80.529999  80.269997  80.459999
 2021-03-22 09:32:00-04:00  80.459999  80.599998  80.360001  80.440002
 2021-03-22 09:33:00-04:00  80.420097  80.565002  80.339996  80.565002
 2021-03-22 09:34:00-04:00  80.559998  80.570099  80.410004  80.510002
 ...                              ...        ...        ...        ...
 2021-03-22 15:55:00-04:00  80.309998  80.319901  80.179901  80.235001
 2021-03-22 15:56:00-04:00  80.220001  80.275200  80.209999  80.224998
 2021-03-22 15:57:00-04:00  80.224998  80.279999  80.190002  80.260002
 2021-03-22 15:58:00-04:00  80.260002  80.260002  80.190002  80.190002
 2021-03-22 15:59:00-04:00  80.195000  80.320000  80.169998  80.290001

                            Adj Close  Volume
 Datetime
 2021-03-22 09:30:00-04:00  80.339996  782808
 2021-03-22 09:31:00-04:00  80.459999  264366
 2021-03-22 09:32:00-04:00  80.440002  279049
 2021-03-22 09:33:00-04:00  80.565002  243177
 2021-03-22 09:34:00-04:00  80.510002  167660
 ...                              ...     ...
 2021-03-22 15:55:00-04:00  80.235001  125160
 2021-03-22 15:56:00-04:00  80.224998  101073
 2021-03-22 15:57:00-04:00  80.260002  125021
 2021-03-22 15:58:00-04:00  80.190002  128241
 2021-03-22 15:59:00-04:00  80.290001  433305

 [390 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-23 09:30:00-04:00  80.129997  80.339996  79.970001  80.209999
 2021-03-23 09:31:00-04:00  80.209999  80.209999  79.699997  79.750000
 2021-03-23 09:32:00-04:00  79.730003  79.730003  79.450104  79.538803
 2021-03-23 09:33:00-04:00  79.845802  79.870003  79.809998  79.860001
 2021-03-23 09:34:00-04:00  79.500000  79.550003  79.480003  79.529999
 ...                              ...        ...        ...        ...
 2021-03-23 15:55:00-04:00  78.449997  78.470001  78.370102  78.389999
 2021-03-23 15:56:00-04:00  78.400002  78.470001  78.349998  78.425003
 2021-03-23 15:57:00-04:00  78.419998  78.434998  78.334999  78.356201
 2021-03-23 15:58:00-04:00  78.349998  78.449997  78.300003  78.430000
 2021-03-23 15:59:00-04:00  78.430000  78.440002  78.320000  78.379997

                            Adj Close  Volume
 Datetime
 2021-03-23 09:30:00-04:00  80.209999  683906
 2021-03-23 09:31:00-04:00  79.750000  238848
 2021-03-23 09:32:00-04:00  79.538803  260423
 2021-03-23 09:33:00-04:00  79.860001  245561
 2021-03-23 09:34:00-04:00  79.529999  143065
 ...                              ...     ...
 2021-03-23 15:55:00-04:00  78.389999  216070
 2021-03-23 15:56:00-04:00  78.425003  187131
 2021-03-23 15:57:00-04:00  78.356201  210547
 2021-03-23 15:58:00-04:00  78.430000  201027
 2021-03-23 15:59:00-04:00  78.379997  370851

 [390 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-24 09:30:00-04:00  77.550003  78.070000  77.540001  77.846397
 2021-03-24 09:31:00-04:00  77.860001  77.860001  77.489998  77.610001
 2021-03-24 09:32:00-04:00  77.650002  78.080002  77.570000  78.050003
 2021-03-24 09:33:00-04:00  78.068497  78.330002  77.959999  78.330002
 2021-03-24 09:34:00-04:00  78.250000  78.309998  78.160004  78.220001
 ...                              ...        ...        ...        ...
 2021-03-24 15:55:00-04:00  76.629997  76.709999  76.519997  76.665001
 2021-03-24 15:56:00-04:00  76.669998  76.690002  76.514999  76.633003
 2021-03-24 15:57:00-04:00  76.635002  76.675003  76.590103  76.620102
 2021-03-24 15:58:00-04:00  76.620003  76.629997  76.474998  76.485001
 2021-03-24 15:59:00-04:00  76.480003  76.540001  76.400002  76.449997

                            Adj Close   Volume
 Datetime
 2021-03-24 09:30:00-04:00  77.846397  1401421
 2021-03-24 09:31:00-04:00  77.610001   269181
 2021-03-24 09:32:00-04:00  78.050003   214898
 2021-03-24 09:33:00-04:00  78.330002   330388
 2021-03-24 09:34:00-04:00  78.220001   286778
 ...                              ...      ...
 2021-03-24 15:55:00-04:00  76.665001   314065
 2021-03-24 15:56:00-04:00  76.633003   381442
 2021-03-24 15:57:00-04:00  76.620102   184102
 2021-03-24 15:58:00-04:00  76.485001   345710
 2021-03-24 15:59:00-04:00  76.449997   566885

 [390 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-25 09:30:00-04:00  75.849998  76.000000  75.330002  75.514999
 2021-03-25 09:31:00-04:00  75.519997  76.099998  75.459999  76.099998
 2021-03-25 09:32:00-04:00  76.110001  76.330002  76.010002  76.300003
 2021-03-25 09:33:00-04:00  76.171997  76.230003  76.129997  76.130096
 2021-03-25 09:34:00-04:00  76.000000  76.040001  75.910004  75.910004
 ...                              ...        ...        ...        ...
 2021-03-25 15:55:00-04:00  76.300003  76.339996  76.205002  76.339996
 2021-03-25 15:56:00-04:00  76.339996  76.339996  76.199997  76.230003
 2021-03-25 15:57:00-04:00  76.239998  76.290001  76.220001  76.264999
 2021-03-25 15:58:00-04:00  76.260002  76.330002  76.250000  76.330002
 2021-03-25 15:59:00-04:00  76.330002  76.360001  76.160103  76.230003

                            Adj Close   Volume
 Datetime
 2021-03-25 09:30:00-04:00  75.514999  1356953
 2021-03-25 09:31:00-04:00  76.099998   312767
 2021-03-25 09:32:00-04:00  76.300003   211102
 2021-03-25 09:33:00-04:00  76.130096   213432
 2021-03-25 09:34:00-04:00  75.910004   217133
 ...                              ...      ...
 2021-03-25 15:55:00-04:00  76.339996   155836
 2021-03-25 15:56:00-04:00  76.230003   145822
 2021-03-25 15:57:00-04:00  76.264999   104358
 2021-03-25 15:58:00-04:00  76.330002   145548
 2021-03-25 15:59:00-04:00  76.230003   395735

 [390 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-26 09:30:00-04:00  76.620003  76.690002  76.209999  76.440002
 2021-03-26 09:31:00-04:00  76.449997  76.610001  76.235001  76.529999
 2021-03-26 09:32:00-04:00  76.529999  76.689903  76.320000  76.480003
 2021-03-26 09:33:00-04:00  76.470001  76.650002  76.349998  76.610001
 2021-03-26 09:34:00-04:00  76.599998  76.629997  76.300003  76.339996
 ...                              ...        ...        ...        ...
 2021-03-26 15:55:00-04:00  76.919998  77.129997  76.900002  77.125000
 2021-03-26 15:56:00-04:00  77.125000  77.150002  76.970001  76.974998
 2021-03-26 15:57:00-04:00  76.974998  77.065002  76.910004  77.029999
 2021-03-26 15:58:00-04:00  77.030098  77.160004  76.980003  77.150002
 2021-03-26 15:59:00-04:00  77.160004  77.499496  77.154999  77.410004

                            Adj Close  Volume
 Datetime
 2021-03-26 09:30:00-04:00  76.440002  788802
 2021-03-26 09:31:00-04:00  76.529999  208117
 2021-03-26 09:32:00-04:00  76.480003  221056
 2021-03-26 09:33:00-04:00  76.610001  155637
 2021-03-26 09:34:00-04:00  76.339996  156558
 ...                              ...     ...
 2021-03-26 15:55:00-04:00  77.125000  356234
 2021-03-26 15:56:00-04:00  76.974998  384927
 2021-03-26 15:57:00-04:00  77.029999  375689
 2021-03-26 15:58:00-04:00  77.150002  342440
 2021-03-26 15:59:00-04:00  77.410004  698326

 [390 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-29 09:30:00-04:00  77.029999  77.099998  76.699997  76.989998
 2021-03-29 09:31:00-04:00  76.985001  77.050003  76.449997  76.482101
 2021-03-29 09:32:00-04:00  76.470001  76.489998  76.269997  76.459999
 2021-03-29 09:33:00-04:00  76.500000  76.539902  76.490097  76.529999
 2021-03-29 09:34:00-04:00  76.669998  76.995003  76.669998  76.995003
 ...                              ...        ...        ...        ...
 2021-03-29 15:55:00-04:00  77.195000  77.199997  77.080002  77.139198
 2021-03-29 15:56:00-04:00  77.139999  77.230003  77.099998  77.190002
 2021-03-29 15:57:00-04:00  77.190002  77.220001  77.135002  77.150002
 2021-03-29 15:58:00-04:00  77.144997  77.154999  77.080002  77.084999
 2021-03-29 15:59:00-04:00  77.089996  77.159897  76.989998  77.150002

                            Adj Close  Volume
 Datetime
 2021-03-29 09:30:00-04:00  76.989998  616440
 2021-03-29 09:31:00-04:00  76.482101  325028
 2021-03-29 09:32:00-04:00  76.459999  220066
 2021-03-29 09:33:00-04:00  76.529999  308692
 2021-03-29 09:34:00-04:00  76.995003  259108
 ...                              ...     ...
 2021-03-29 15:55:00-04:00  77.139198  115982
 2021-03-29 15:56:00-04:00  77.190002  118366
 2021-03-29 15:57:00-04:00  77.150002  219630
 2021-03-29 15:58:00-04:00  77.084999  231186
 2021-03-29 15:59:00-04:00  77.150002  371294

 [388 rows x 6 columns],
                                 Open       High        Low      Close  \
 Datetime
 2021-03-30 09:30:00-04:00  76.470001  76.559998  76.059998  76.159897
 2021-03-30 09:31:00-04:00  76.139999  76.219902  75.900002  75.913399
 2021-03-30 09:32:00-04:00  75.910004  76.080002  75.769997  75.862503
 2021-03-30 09:33:00-04:00  75.680000  75.750000  75.680000  75.739998
 2021-03-30 09:34:00-04:00  75.625000  75.625000  75.570000  75.570000
 ...                              ...        ...        ...        ...
 2021-03-30 15:55:00-04:00  75.735001  75.779999  75.629997  75.650002
 2021-03-30 15:56:00-04:00  75.650002  75.754997  75.589996  75.750000
 2021-03-30 15:57:00-04:00  75.750000  75.800003  75.730003  75.769997
 2021-03-30 15:58:00-04:00  75.769997  75.815002  75.730003  75.815002
 2021-03-30 15:59:00-04:00  75.820000  76.019997  75.790001  76.010002

                            Adj Close  Volume
 Datetime